// Decompiled by DJ v3.12.12.98 Copyright 2014 Atanas Neshkov  Date: 17/11/2017 7:06:57 p. m.
// Home Page: http://www.neshkov.com/dj.html - Check often for new version!
// Decompiler options: packimports(3) 
// Source File Name:   RESULTADO_VERIFICACION.java
package co.com.andesscd.pki.clases;

public enum RESULTADO_VERIFICACION {
    VALIDO, OCSP_CRL_FUERA_DE_LINEA, CTL_NO_VALIDO, CTL_ERROR_FIRMA, CTL_ERROR_TIEMPO, CADENA_INCOMPLETA, TIENE_RESTRICCION_DE_NOMBRE_EXCLUIDA, TIENE_RESTRICCION_DE_NOMBRE_NO_PERMITIDA, TIENE_RESTRICCION_DE_NOMBRE_NO_DEFINIDA, TIENE_RESTRICCION_DE_NOMBRE_NO_SOPORTADA, RESTRICCION_DE_NOMBRE_INVALIDA, RESTRICCION_BASICA_INVALIDA, RESTRICCION_DE_POLITICAS_INVALIDA, EXTENCION_INVALIDA, CADENA_CICLICA, ESTADO_DE_REVOCACION_DESCONOCIDO, RAIZ_NO_CONFIABLE, USO_NO_VALIDO, FIRMA_DE_CERTIFICADO_NO_VALIDA, CADENA_DE_TIEMPO_INVALIDA, CERTIFICADO_EXPIRADO, CERTIFICADO_AUN_NO_VALIDO, CERTIFICADO_REVOCADO, SIN_ERROR, DOCUMENTO_ORIGINAL_MODIFICADO, FECHA_FIRMA_INCORRECTA, FIRMADO_EN_EL_FUTURO, SNTP_NO_DISPONIBLE, ERROR_DESCONOCIDO, SIN_INFORMACION_OCSP, TIMESTAMP_NO_CONFIABLE, TIMESTAMP_NO_CORRESPONDE, TIMESTAMP_ERROR_DE_VALIDACION, FECHA_FIRMA_DESCONOCIDA, CERTIFICADO_NO_ENCONTRADO;
}
